from __future__ import annotations

from typing import Protocol

from ...models.auth import AuthPrinciple
from ...models.deployment import Deployment
from ...models.model import LLMModel, Provider


class ModelRepository(Protocol):
    async def add(self, model: LLMModel) -> None: ...

    async def get(self, model_id: str) -> LLMModel: ...

    async def get_for_provider(self, provider: Provider) -> list[LLMModel]: ...

    async def list(self) -> list[LLMModel]: ...

    async def remove(self, model_id: str) -> None: ...

    async def exists(self, model_id: str) -> bool: ...


class DeploymentRepository(Protocol):
    async def add(self, deployment: Deployment) -> None: ...

    async def get(self, deployment_id: str) -> Deployment: ...

    async def get_for_model(self, model_id: str) -> list[Deployment]: ...

    async def list(self) -> list[Deployment]: ...

    async def remove(self, deployment_id: str) -> None: ...

    async def exists(self, deployment_id: str) -> bool: ...


class AuthRepository(Protocol):
    async def add(self, principle: AuthPrinciple) -> None: ...

    async def get(self, auth_id: str) -> AuthPrinciple: ...

    async def list(self) -> list[AuthPrinciple]: ...

    async def remove(self, auth_id: str) -> None: ...

    async def exists(self, auth_id: str) -> bool: ...
